### PR TITLE
Swap WebView with AdvancedWebView to support file upload

### PR DESCRIPTION
**Pull request by jstorq**
Changes to support fileInput control capability 'out-of-the-box' in WebView control.  Basically, use the AdvancedWebView which supports this functionality where the default WebView does not.

### CODE REVIEW

**Comment by clsource** [comment]
Thanks for this PR. 👍

**Comment by clsource** [comment]
I made some tests and this is working fine.
This weekend I will merge it

**Comment by jstorq** [comment]
Excellent.  Thanks.

**Comment by clsource** [comment]
Please @DuckProjects take a look too :) thanks

**Comment by clsource** [comment]
I had to revert this PR because it was having troubles with $agents and other actions.
So it was saved to an alternative branch.

Is better for advanced webview to be a new component and do not replace the current implementation entirely.
So people that explicitily needs this feature can still access it, but it may have some untested behaviours.

Thanks for your code and time invested in this. It will still be considered for the future 👍

**Comment by avnermosh** [comment]
I had the exact same problem, where the input file button, would not respond in jasonnete (but works fine in the regular web-app).
I described my problem in https://t.me/jasonelle/6700
After I switched to this branch, it responds properly and I can select a file from my device.

@jstorq thank you for making this code change
@clsource thank you for maintaining this branch.

**Pull request merged**
