### PR TITLE
Bug/agents clearing

### PR DESCRIPTION
**Pull request by kcorey**
Reinstalls the agents in onResume.  Seems to fix the 'Agents stop working when showing another window' bug.

### CODE REVIEW

**Comment by panterozo** [comment]
Hi @kcorey.. What case are you trying to solve?.. Please refer to the bug if it is one.

**Comment by kcorey** [comment]
> Hi @kcorey.. What case are you trying to solve?.. Please refer to the bug if it is one, or give more information about the bug

This pull request seems to answer a couple bugs about agents stopping work when the current activity loses focus.

https://github.com/jasonelle/jasonelle/issues/33
https://github.com/jasonelle/jasonelle/issues/64

**Comment by clsource** [comment]
Thanks @kcorey this code will be considered in futher versions. I'll keep you touched when the next version begins :)

**Comment by clsource** [comment]
Thanks @kcorey it was merged :)

**Pull request closed without merging**
